### ISSUE TITLE
No output?

### ISSUE THREAD

**Issue by amustill** [deployphp/action#7]
Firstly, it's great to see an official action for Deployer.

However, I'm wondering if there is a reason behind the decision to suppress output from the commands? Personally, having used Deployer in other CI/CD environments, it's incredibly useful to see the output for debugging reasons.

I regularly use the `--revision` argument when deploying to non-production environments, so getting confirmation from Deployer of the revision used is super useful.

**Comment by antonmedv** [comment]
I didn’t get it) please explain

**Comment by amustill** [comment]
When using this action output from the commands are not logged to the workflow log. It simply runs silently, showing `Run deployphp/action` with no output from the command.

Attached is a screenshot showing the action running without any output logged - simply, I can't see what tasks are being run. Above you will see output from a `composer install` command, for example.

<img width="602" alt="deployerphp-action" src="https://user-images.githubusercontent.com/448157/107844704-c1147a00-6dcd-11eb-877e-ea9142d53be5.png">

I believe this has to do with using `execa` and not [piping the output](https://github.com/sindresorhus/execa#pipe-the-child-process-stdout-to-the-parent) back to the Node process.

**Comment by antonmedv** [comment]
Yes you are right. This should be fixed and output MUST be logged.

**Comment by lptn** [comment]
@amustill 
>I regularly use the --revision argument when deploying to non-production environments, so getting confirmation from Deployer of the revision used is super useful.

BTW, how to you specify a revision? I use `deploy somehost --revision=$GITHUB_SHA -vvv`  but it doesn't resolve `$GITHUB_SHA` into a string (tried different approaches)

**Comment by amustill** [comment]
@lptn I too have been using `--revision="$GITHUB_SHA"` but without output I cannot see how it resolves!

I'm currently only using this action on one project (I normally use GitLab CI/CD) so I haven't had the opportunity to fully test its capabilities.
